apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-deployment
  labels:
    app: lanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete
  template:
    metadata:
      labels:
        app: lanchonete
    spec:
      containers:
        - name: container-lanchonete
          image: piovezan1207/techchallenger-lanchonete-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP 
          envFrom:
            - configMapRef:
                name: lanchonete-configmap
            - secretRef:
                name: lanchonete-secret
          resources:
            requests:
              cpu: 40m