apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonete-configmap
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://tc-mysql.caly75dbfwbq.us-east-1.rds.amazonaws.com:3306/lanchonete_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
