apiVersion: v1
kind: Service
metadata:
  name: api-lanchonete-lb
  labels:
    app: api-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: lanchonete-deployment
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
